### PR TITLE
Migration website from gatsby to docusaurus with all pages and configs

### PR DESCRIPTION
**Pull request by tito12**
This PR was created according to the issues which are connected:
https://github.com/OpenLineage/website/issues/91
https://github.com/OpenLineage/website/issues/92
https://github.com/OpenLineage/website/issues/93

This PR contain migrating files from gatsby website to docosaurus platform as:
- home page 
- blog pages
- base pages
- specs
- navigation
- footer
- config (seo, deploy, packages)
- updated readme
- plugin for ability to show blogs on home page
- css tailwind 
- static files
- theme switcher adapted for all pages
- removed unused code

screencapture-localhost-3000-2023-03-07-16_12_25

### CODE REVIEW

**Comment by rossturk** [comment]
First, thank you for doing this! It looks like a lot of work, and it seems to be quite functional. That said, I notice a few issues:

1. Links do not seem to be colored as they were in the old site. Look at the Resources page - I believe in the old system it was accomplished with the following CSS:

```
    .post-content a {
        --tw-text-opacity: 1;
        color: rgba(116, 164, 188, var(--tw-text-opacity));
        margin-bottom: 1rem;
        margin-top:1rem
    }
```

2. Is it possible to have the footer split across two menus like in the original? The first line was internal links and the second was external links, and now they are all on a single line. I think it's a bit long.

3. Would it be possible to have the Blog landing page render the posts in grid layout, like the original? This isn't a big deal if it's too difficult to achieve.

4. The styling on the Ecosystem page does not match the original - tables have full borders instead of just horizontal borders, and the text size seems to be off.

Thanks!

**Comment by tito12** [comment]
Thanks for your review and attention to detail that I did not notice @rossturk 
Added changes, and updated Blog page to custom style with grid style, it was not a problem, but took a little bit time.

**Review by rossturk — APPROVED** [review]

**Comment by rossturk** [comment]
Nice! Thanks @tito12, I appreciate the effort. It all looks good to me now.

As for how we handle deploying these changes, I think: 
1. Remove `cname: openlineage.io` from the `peaceiris/actions-gh-pages@v3` workflow in the website repo & trigger it with a merge.
2. Verify that `openlineage.io` stops working 😄 
3. Add the same cname config to this repo, in this pull request, so it gets configured once this is pushed
4. Merge this pull request
5. Verify that `openlineage.io` starts working
6. Update the release script in the main repo: https://github.com/OpenLineage/OpenLineage/blob/6bbde6eabec870fe3f862ea0b1da08a963d2e2c7/spec/release.sh#L16

WDYT? Does this sound like the correct sequence? If so, can you do #3 in this pull request and I can take care of the rest?

**Comment by rossturk** [comment]
I think I will do the deployment in a slightly different order:
1. Remove `cname: openlineage.io` from the peaceiris/actions-gh-pages@v3 workflow in the website repo & trigger it with a merge.
2. Verify that openlineage.io stops working 😄
3. Merge this pull request
4. Add the same cname config to this repo, in a separate pull request
5. Verify that openlineage.io starts working
6. Update the release script in the main repo: https://github.com/OpenLineage/OpenLineage/blob/6bbde6eabec870fe3f862ea0b1da08a963d2e2c7/spec/release.sh#L16

Going to give it a try now :)

**Comment by tito12** [comment]
Hard to say from my side about deployment, I hope sequence is correct. 
Saw that you merged and hope that everything is okay :)

**Pull request merged**
